### ISSUE TITLE
Added space in prototype pages

### ISSUE THREAD

**Issue by brianjo** [pytorch/pytorch_sphinx_theme#101]
Not sure if this is caused by the theme updates, but we have a lot of space added between the text at the top of the page and the topic selector on the prototype pages. 

<img width="1312" alt="Screen Shot 2021-03-04 at 12 44 55 AM" src="https://user-images.githubusercontent.com/1500149/109917304-13d1ab00-7c83-11eb-9868-cc738682cc27.png">
 

https://deploy-preview-1390--pytorch-tutorials-preview.netlify.app/prototype/prototype_index.html

@Bgreen23

**Comment by Bgreen23** [comment]
Hey @brianjo, singular article sections have a minimum height applied to them which is why there is a large gap between the text and the topic selector. I attached a screenshot that shows the generated CSS for the article section. One potential fix is to change the article tag to a div to remove the minimum height.


![Screen Shot 2021-03-04 at 9 52 45 AM](https://user-images.githubusercontent.com/31549535/109981927-63d65f00-7ccf-11eb-9757-6f400ec92895.png)

**Comment by brianjo** [comment]
> Hey @brianjo, singular article sections have a minimum height applied to them which is why there is a large gap between the text and the topic selector. I attached a screenshot that shows the generated CSS for the article section. One potential fix is to change the article tag to a div to remove the minimum height.
> 
> ![Screen Shot 2021-03-04 at 9 52 45 AM](https://user-images.githubusercontent.com/31549535/109981927-63d65f00-7ccf-11eb-9757-6f400ec92895.png)

Thanks Brandon. Can you submit a PR with a fix?

**Comment by Bgreen23** [comment]
Hey @brianjo here's the PR to fix this issue #102. That PR removes the `min-height` that's affecting the PyTorch Recipes. In the PR I mentioned keeping the `min-height` for the `pytorch-left-content` class due to the removal of it reintroducing the artifacting white space. I wanted to expand on that here in the issue. 

That property is kept to keep the footer from jumping on pages where the content does not fill the initial height of the screen. Setting the `min-height` keeps the footer in a consistent place instead of jumping up and down. The trade-off is on those pages there is space between the "copyright" text and the footer. 

**Note:** On pages where the content expands past the initial page height, i.e., you have to scroll, there is no space as the `min-height` has no effect on the page. 

Removing that space is something we can look into but it may be a heavy lift as it will most likely require us to look into and change the way element heights are being calculated across the Docs. 

Let me know if you have any questions about this or need any additional information!

**Comment by brianjo** [comment]
Thanks so much Brandon! I'll merge this and rebuild tutorials a little later. @Bgreen23

**Comment by brianjo** [comment]
Looks like we're still seeing the issue. Can you look at it again @Bgreen23? I built the tutorial site last night a few hours after I merged #102. Thanks!

**Comment by Bgreen23** [comment]
@brianjo I rebuilt the theme CSS file in #103. This should take care of `min-height` still showing up

**Comment by brianjo** [comment]
Awesome! Thanks. I'll give it a go.

**Comment by brianjo** [comment]
Hey Brandon, I don't think the updated theme.css is making it to the https://github.com/pytorch/tutorials/tree/gh-pages/_static/css folder. Is that something to do with how it's installing or should I just copy the file over to fix things? @Bgreen23

**Comment by Bgreen23** [comment]
@brianjo That's very interesting. I'm not sure why that's not adjusting the current static CSS file. Removing lines 10559-10561 in this file https://github.com/pytorch/pytorch_sphinx_theme/blob/master/pytorch_sphinx_theme/static/css/theme.css will solve the issue. Those lines are responsible for adding the extra space after the section.

<img width="1359" alt="Screen Shot 2021-03-05 at 2 32 49 PM" src="https://user-images.githubusercontent.com/31549535/110164810-e50d1f00-7dbf-11eb-8e77-fe5fe78b506f.png">

**Comment by brianjo** [comment]
Thanks Brandon! I made the change to the current css and that took care of the issue. @Bgreen23
