### ISSUE TITLE
Support for sphinx >= 3

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/pytorch_sphinx_theme#115]
All of Pytorch, torchaudio, torchtext, and torchvision pin the sphinx version to 2.4.4 because of rendering issues when ugprading to sphinx 3 (https://github.com/pytorch/audio/pull/972, https://github.com/pytorch/vision/issues/3681)

For example this signature renders fine in 2.4.4:

![image](https://user-images.githubusercontent.com/1190450/115861968-6cbff300-a42b-11eb-8605-76cdeb65caee.png)

But it doesn't render properly with sphinx 3 (various annotations are missing, etc.):

![image](https://user-images.githubusercontent.com/1190450/115861989-73e70100-a42b-11eb-8735-d4ffcdd981ef.png)

Are there plans to add support for `sphinx>=3`?

CC @brianjo @holly1238

**Comment by mthrok** [comment]
@NicolasHug @brianjo 

This is caused by `position: absolute` of `article.pytorch-article .function dt a, article.pytorch-article .attribute dt a, article.pytorch-article .class .attribute dt a, article.pytorch-article .class dt a` selection. In chrome, removing this attribute makes it work.

<img width="1618" alt="Screen Shot 2021-06-03 at 17 00 06" src="https://user-images.githubusercontent.com/855818/120712202-5a0af600-c48e-11eb-904e-bd55bbddf056.png">

<img width="1614" alt="Screen Shot 2021-06-03 at 16 59 59" src="https://user-images.githubusercontent.com/855818/120712210-5d9e7d00-c48e-11eb-9f93-a51721e42526.png">

If I do `for file in $(grep -l 'position: absolute' $(find . -type f -name '*css')); do sed -i '' '/position: absolute;/d' $file; done` and remove `position: absolute`, then the issue gets resolved.

I think the following line is causing the issue, but someone needs to build CSS and verify.

https://github.com/pytorch/pytorch_sphinx_theme/blob/0efb4da5030c0462a5493a3db6b80317116d6c3e/scss/_sphinx_base.scss#L377

**Comment by brianjo** [comment]
We actually moved to 3.5.4 for docs, so I think we're good now. https://github.com/pytorch/pytorch/blob/master/docs/requirements.txt

**Comment by NicolasHug** [comment]
@brianjo  No, sphinx 3 is still broken for type annotations, please see https://github.com/pytorch/pytorch_sphinx_theme/pull/134#issuecomment-890308988 and https://github.com/pytorch/pytorch_sphinx_theme/pull/134#issuecomment-891071535

Pytorch docs will be broken as soon as they start having signatures with  type annotations.

**Comment by garymm** [comment]
There's a 1 line fixed suggested [above](https://github.com/pytorch/pytorch_sphinx_theme/issues/115#issuecomment-854192543). @NicolasHug can you try it out and send a PR if it fixes the issue?

**Comment by NicolasHug** [comment]
Sorry, I have zero css ability, so unfortunately I can't assess the suitability of the proposed solution
